version: '2.2'
services:
    database:
        image: mysql:8-oracle
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_USER: lulu
            MYSQL_ROOT_PASSWORD: passwod
            MYSQL_DATABASE: userdb
            MYSQL_USER: lulu
            MYSQL_PASSWORD: password
            
    adminer:
        image: adminer:4
        ports:
          - 8086:8080